config/routes.rb
Vatatis::Application.routes.draw do
  root to: "atis#home"

  get "/metar", to: "atis#metar", as: :metar
  post "/metar", to: "atis#decode"
  get "/:token", to: "atis#home", as: :home_with_token
  get "/:token/:icao", to: "atis#decode", as: :atis_with_token
  get "/atis/:icao", to: "atis#decode", as: :atis

  resources :tokens

end

app/models/airport.rb
class Airport < ActiveRecord::Base


end

app/models/token.rb
class Token < ActiveRecord::Base

  serialize :params

  validates_presence_of :token

  after_initialize do |t|
    t.token ||= SecureRandom.hex(3).upcase
    t.params ||= {
        pl: "en",
        apptype: [],
        extra: []
    }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atis_controller.rb
class AtisController < ApplicationController

  def home

    @token = Token.where(token: params[:token]).first if params[:token].present?
    @token ||= Token.new

  end

  def decode

    @message = ATIS::Message.new(params[:metar]||params[:icao], metar_options_from_params)

    respond_to do |format|
      format.html
      format.text
    end
  end

  def metar

  end

  private

  def metar_options_from_params
    @token = Token.where(token: params[:token]).first if params[:token].present?

    options = ((@token && @token.params) || {}).with_indifferent_access
    options[:lang] = [@token.params[:pl], @token.params[:sl]].reject { |l| l.blank? } if @token.present?
    options.merge! token_options_to_arrays if @token.present?
    options.merge! params_split_to_arrays

    {
        arrival_runways: options[:arr],
        approach_types: options[:apptype],
        departure_runways: options[:dep],
        index: options[:info].try(:downcase),
        transition_level: options[:trlvl],
        extra: options[:extra],
        report_pressure_in: options[:pt],
        languages: options[:lang],
        closed_runways: options[:c_rwys],
        closed_taxiways: options[:c_twys]
    }
  end

  def params_split_to_arrays
    [:arr, :apptype, :dep, :extra, :pt, :lang, :c_rwys, :c_twys].each do |key|
      params[key] = params[key].split(",").map(&:strip) if params[key].is_a?(String)
    end
    params
  end

  def token_options_to_arrays
    {
        c_rwys: @token.params[:c_rwys].to_s.split(",").map(&:strip),
        c_twys: @token.params[:c_twys].to_s.split(",").map(&:strip)
    }
  end

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController

  def create
    token = Token.new(params: token_params)
    token.save
    redirect_to home_with_token_path(token: token.token)
  end

  def update
    token = Token.find(params[:id])
    token.update_attributes! params: token_params
    redirect_to home_with_token_path(token: token.token)
  end

  private

  def token_params
    params.permit(:pl, :sl, :trlvl, :c_rwys, :c_twys, pt: [], apptype: [], extra: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def euroscope_url
    str = home_with_token_url(token: @token.token)
    str += "/$atisairport.txt?arr=$arrrwy($atisairport)&dep=$deprwy($atisairport)&info=$atiscode"
    str

  end

end

app/helpers/metar_helper.rb
module MetarHelper
end

app/views/atis/_table.html.haml
- metar.groups.each do |name|
  - group = metar.send(name)
  %h4= name
  %table.table.table-condensed.table-striped.table-bordered
    - group.each_with_index do |node, index|
      - if index == 0
        %tr
          - node.properties.each do |property|
            %th= property
      %tr
        - node.properties.each do |property|
          %td= node.send(property)

app/views/atis/decode.html.haml
.container
  .row
    .col-md-12
      .well.lead= @message.metar.full_report

  .row
    .col-md-12
      - @message.languages.each do |lang|
        .well= @message.render_in lang.to_sym

  .row
    .col-md-12
      %h3 DATA
  .row
    .col-md-12= render "atis/table", metar: @message.metar

app/views/atis/decode.text.erb
<%
  @message.languages.each do |lang|
    concat @message.render_in(lang.to_sym).encode("windows-1251")
  end
%>

app/views/atis/home.html.haml
.row
  .col-md-10.col-md-offset-1
    .page-header
      %h1.text-center
        vATIS
        %small VATSIM ATIS generator

.row
  .col-md-10.col-md-offset-1
    #result.text-center{style: ("display: none;" if @token.new_record?)}
      %p.title Euroscope ATIS Maker URL:
      %p.url= euroscope_url

.row
  .col-md-6.col-md-offset-3

    = form_for @token, html: { class: "form-horizontal" } do

      - languages = { "Английский" => "en", "Русский" => "ru" }
      .form-group
        %label.col-md-4.control-label Основной Язык
        .col-md-8
          = select_tag :pl, options_for_select(languages, @token.params[:pl]), class: "form-control"

      .form-group
        %label.col-md-4.control-label Дополнительный Язык
        .col-md-8
          = select_tag :sl, options_for_select(languages, @token.params[:sl]), include_blank: true, class: "form-control"

      .form-group
        %label.col-md-4.control-label Типы Захода
        .col-md-3
          .checkbox
            = check_box_tag "apptype[]", "ils", @token.params[:apptype].include?("ils")
            ИЛС
          .checkbox
            = check_box_tag "apptype[]", "2ndb", @token.params[:apptype].include?("2ndb")
            ОСП
          .checkbox
            = check_box_tag "apptype[]", "vis", @token.params[:apptype].include?("vis")
            Визуальный
          .checkbox
            = check_box_tag "apptype[]", "loc", @token.params[:apptype].include?("loc")
            КРМ
          .checkbox
            = check_box_tag "apptype[]", "ndb", @token.params[:apptype].include?("ndb")
            ОПРС
        .col-md-5
          .checkbox
            = check_box_tag "apptype[]", "rev_ndb", @token.params[:apptype].include?("rev_ndb")
            ОПРС Обратного Старта
          .checkbox
            = check_box_tag "apptype[]", "vordme", @token.params[:apptype].include?("vordme")
            ВОР ДМЕ
          .checkbox
            = check_box_tag "apptype[]", "gnss", @token.params[:apptype].include?("gnss")
            СНС
          .checkbox
            = check_box_tag "apptype[]", "par", @token.params[:apptype].include?("par")
            РСП


      .form-group
        %label.col-md-4.control-label Дополнительная Информация
        .col-md-8
          .checkbox
            = check_box_tag "extra[]", "birds", @token.params[:extra].try(:include?, "birds")
            Птицы
        .col-md-8
          .checkbox
            = check_box_tag "extra[]", "lvp", @token.params[:extra].try(:include?, "lvp")
            Процедуры Пониженной Видимости

      .form-group
        %label.col-md-4.control-label Эшелон Перехода
        .col-md-8
          = text_field_tag :trlvl, @token.params[:trlvl], class: "form-control"

      .form-group
        %label.col-md-4.control-label Закрытые ВПП
        .col-md-8
          = text_field_tag :c_rwys, @token.params[:c_rwys], class: "form-control"

      .form-group
        %label.col-md-4.control-label Закрытые РД
        .col-md-8
          = text_field_tag :c_twys, @token.params[:c_twys], class: "form-control"

      .form-group
        %label.col-md-4.control-label Давление в:
        .col-md-8
          .checkbox
            = check_box_tag "pt[]", "qfe", @token.params[:pt].try(:include?, "qfe")
            QFE

          .checkbox
            = check_box_tag "pt[]", "qnh", @token.params[:pt].try(:include?, "qnh")
            QNH

      .form-group
        .col-md-8.col-md-offset-4
          - submit_message = @token.new_record? ? "Создать Новый Код" : "Сохранить Изменения"
          = submit_tag submit_message, class: "btn btn-primary"

app/views/atis/metar.html.haml
.row
  .col-md-10.col-md-offset-1
    .page-header
      %h1.text-center
        METAR Analyzer

= form_tag metar_path, method: :post do
  .row
    .col-md-10.col-md-offset-1
      .form-group
        = text_field_tag :icao, nil, placeholder: "ICAO Airport code or METAR string", class: "form-control"

  .row
    .col-md-4.col-md-offset-4
      = submit_tag "Continue", name: nil, class: "btn btn-primary btn-block"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title vATIS
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      = yield

app/views/metar/decode.html.haml
.container
  .row
    .col-md-12
      .well.lead= @message.metar.full_report

  .row
    .col-md-12
      - @message.languages.each do |lang|
        .well= @message.render_in lang.to_sym

  .row
    .col-md-12
      %h3 DATA
  .row
    .col-md-12= render "metar/table", metar: @message.metar